import os
import csv
import pickle
from typing import List, Dict

from gensim.summarization import bm25
from openai import OpenAI
from langchain_core.example_selectors.base import BaseExampleSelector
from langchain_core.prompts.few_shot import FewShotPromptTemplate
from langchain_core.prompts.prompt import PromptTemplate


# ==============================
# Configuration
# ==============================

OPENAI_API_KEY = "YOUR_API_KEY_HERE"
MODEL_NAME = "gpt-4o-mini"
NUM_EXAMPLES_PER_CLASS = 2   # 2 Human + 2 AI = 4 total

os.environ["OPENAI_API_KEY"] = OPENAI_API_KEY
client = OpenAI()


# ==============================
# Utility Functions
# ==============================

def escape_curly_braces(text: str) -> str:
    """
    Escape curly braces so they don't break LangChain prompt formatting.
    """
    return str(text).replace("{", "{{").replace("}", "}}")


def clean_model_output(output: str) -> str:
    """
    Ensure the model output is strictly '0' or '1'.
    """
    output = output.strip()
    return "1" if "1" in output else "0"


# ==============================
# Custom Example Selector
# ==============================

class BM25ExampleSelector(BaseExampleSelector):
    """
    Selects top-k similar examples using BM25 similarity.
    Ensures balanced examples (equal Human and AI).
    """

    def __init__(self, examples: List[Dict]):
        self.examples = examples

    def add_example(self, example: Dict):
        self.examples.append(example)

    def _tokenize(self, text: str) -> List[str]:
        """
        Simple whitespace tokenizer.
        """
        return str(text).split()

    def select_examples(self, input_variables: Dict) -> List[Dict]:
        """
        Select top similar examples to the input query.
        """

        query_code = input_variables["input"]

        # Tokenize training corpus
        tokenized_corpus = [
            self._tokenize(example["input"])
            for example in self.examples
        ]

        bm25_model = bm25.BM25(tokenized_corpus)

        query_tokens = self._tokenize(query_code)

        # Compute average IDF (required by gensim BM25)
        average_idf = sum(
            float(bm25_model.idf[word])
            for word in bm25_model.idf.keys()
        ) / len(bm25_model.idf.keys())

        # Get similarity scores
        scores = bm25_model.get_scores(query_tokens, average_idf)

        # Rank examples by score (highest first)
        ranked_indices = sorted(
            range(len(scores)),
            key=lambda i: scores[i],
            reverse=True
        )

        ranked_examples = [self.examples[i] for i in ranked_indices]

        # Select balanced examples
        human_examples = [
            ex for ex in ranked_examples if ex["output"] == 1
        ][:NUM_EXAMPLES_PER_CLASS]

        ai_examples = [
            ex for ex in ranked_examples if ex["output"] == 0
        ][:NUM_EXAMPLES_PER_CLASS]

        selected = human_examples + ai_examples

        # Escape curly braces for prompt safety
        formatted_examples = [
            {
                "input": escape_curly_braces(ex["input"]),
                "output": ex["output"]
            }
            for ex in selected
        ]

        return formatted_examples


# ==============================
# Classification Function
# ==============================

def classify_code(
    test_example: Dict,
    training_examples: List[Dict],
    language: str
) -> str:
    """
    Classify a single code snippet using retrieval-based few-shot prompting.
    """

    example_selector = BM25ExampleSelector(training_examples)

    # Define how examples appear in the prompt
    example_prompt = PromptTemplate.from_template(
        "Input:\n{input}\nOutput: {output}\n"
    )

    # Build few-shot prompt template
    prompt_template = FewShotPromptTemplate(
        example_selector=example_selector,
        example_prompt=example_prompt,
        prefix=f"""
You are a strict binary classifier.

Task:
Determine whether the following {language} source code
is generated by a Human or an AI model.

Output Rules:
- Return 1 → if Human
- Return 0 → if AI
- Return ONLY a single digit (0 or 1)
- Do NOT include explanation
""",
        suffix="Input:\n{input}\nOutput:",
        input_variables=["input"]
    )

    # Format final prompt
    query_code = escape_curly_braces(test_example["input"])
    final_prompt = prompt_template.format(input=query_code)

    # Call OpenAI API
    response = client.chat.completions.create(
        model=MODEL_NAME,
        temperature=0,
        messages=[{"role": "user", "content": final_prompt}]
    )

    raw_output = response.choices[0].message.content

    return clean_model_output(raw_output)


# ==============================
# Main Execution Loop
# ==============================

def run_experiment(
    train_path: str,
    test_path: str,
    output_csv_path: str,
    language: str
):
    """
    Run classification experiment over test set.
    """

    # Load datasets
    with open(train_path, "rb") as f:
        training_examples = pickle.load(f)

    with open(test_path, "rb") as f:
        test_examples = pickle.load(f)

    # Prepare CSV writer
    with open(output_csv_path, "w", newline="") as csvfile:
        writer = csv.writer(csvfile)
        writer.writerow(["index", "code", "true_label", "prediction"])

        # Process each test example
        for i, test_example in enumerate(test_examples):

            prediction = classify_code(
                test_example,
                training_examples,
                language
            )

            writer.writerow([
                i,
                test_example["input"],
                test_example["output"],
                prediction
            ])

            print(f"[{i}] Prediction completed.")


# ==============================
# Example Usage
# ==============================

if __name__ == "__main__":

    run_experiment(
        train_path="train.pkl",
        test_path="test.pkl",
        output_csv_path="results.csv",
        language="Java"
    )