
import os
import pandas as pd
from openai import OpenAI
from dotenv import load_dotenv

# Load environment variables from .env
load_dotenv()


client = OpenAI(
    api_key=os.environ.get("OPENAI_API_KEY"),
)

def predict_code(row):
    language = row["language"]
    code = row["contrast"]
    response = client.chat.completions.create(
        model="gpt-3.5-turbo",
        messages=[
            {"role": "system", "content": f"You will be provided with a {language} source code. Please determine if the source code is generated by Artificial intelligence (AI) models (i.e. language models) or human. If the code is generated by human, label it as 1. If the code is generated by AI, label is a 0. Return the label only in the output."},
            {"role": "user", "content": f"Determine whether this code is generated by human or AI and return the label."},
            {"role": "user", "content": f"Code:\n{str(code)}"}
        ]
    )
    return response.choices[0].message.content.strip()


if __name__ == "__main__":
    sample_data = pd.read_json("data/sample_data.jsonl", lines=True)
    data = sample_data.sample(n=10)
    data["prediction"] = data.apply(predict_code, axis=1)
    data.to_csv("data/predictions.csv", index=False)
    print(data.head(50))

